/**
 * @fileoverview gRPC-Web generated client stub for jwt
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.3
// source: Protos/jwt.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as Protos_jwt_pb from '../Protos/jwt_pb';


export class OpenServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetToken = new grpcWeb.MethodDescriptor(
    '/jwt.OpenService/GetToken',
    grpcWeb.MethodType.UNARY,
    Protos_jwt_pb.User,
    Protos_jwt_pb.Reply,
    (request: Protos_jwt_pb.User) => {
      return request.serializeBinary();
    },
    Protos_jwt_pb.Reply.deserializeBinary
  );

  getToken(
    request: Protos_jwt_pb.User,
    metadata: grpcWeb.Metadata | null): Promise<Protos_jwt_pb.Reply>;

  getToken(
    request: Protos_jwt_pb.User,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Protos_jwt_pb.Reply) => void): grpcWeb.ClientReadableStream<Protos_jwt_pb.Reply>;

  getToken(
    request: Protos_jwt_pb.User,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Protos_jwt_pb.Reply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/jwt.OpenService/GetToken',
        request,
        metadata || {},
        this.methodDescriptorGetToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/jwt.OpenService/GetToken',
    request,
    metadata || {},
    this.methodDescriptorGetToken);
  }

}

