/**
 * @fileoverview gRPC-Web generated client stub for test
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.3
// source: Protos/test.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as Protos_test_pb from '../Protos/test_pb';


export class PrivateServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetSecret = new grpcWeb.MethodDescriptor(
    '/test.PrivateService/GetSecret',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    Protos_test_pb.SecretReply,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    Protos_test_pb.SecretReply.deserializeBinary
  );

  getSecret(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<Protos_test_pb.SecretReply>;

  getSecret(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Protos_test_pb.SecretReply) => void): grpcWeb.ClientReadableStream<Protos_test_pb.SecretReply>;

  getSecret(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Protos_test_pb.SecretReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/test.PrivateService/GetSecret',
        request,
        metadata || {},
        this.methodDescriptorGetSecret,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/test.PrivateService/GetSecret',
    request,
    metadata || {},
    this.methodDescriptorGetSecret);
  }

}

